### ISSUE TITLE
Upgrade ffi to 1.0.0

### ISSUE THREAD

**Issue by narumishi** [ekibun/flutter_qjs#12]
current `master` and `dev` branch of `flutter` is not compatible with `ffi 0.1.3`, almost all packages depends on ffi and ffi itself will build failed. It was warning before not error.
```
...../win32-1.7.4/lib/src/structs.dart:2999:7: Error: Struct 'NLM_SIMULATED_PROFILE_INFO' is empty. Empty structs are undefined behavior.
class NLM_SIMULATED_PROFILE_INFO extends Struct {}                      
      ^                                                                 
...../ffi-0.1.3/lib/src/allocation.dart:47:33: Error: Expected type 'T' to be a valid and instantiated subtype of 'NativeType'.
  final int totalSize = count * sizeOf<T>();
```
The top level functions `free` and `allocate` are moved into abstract class in `ffi 1.0.0`

**Comment by narumishi** [comment]
maybe related issue
https://github.com/dart-lang/sdk/issues/44622
https://github.com/dart-lang/sdk/issues/44621

**Comment by ekibun** [comment]
Thanks!

**Comment by narumishi** [comment]
BTW, when building/hot restart an app with this qjs package, a lot of warnings (mostly number type related like `long`, `int`, `size_t`) will be generated. 

Is this usual and allowed for c/c++ program without type cast? I am not familiar with c++, just try to clear the doubts. Thanks.

**Comment by Sunbreak** [comment]
Wonderful project!

Have you encounter array problem in `Struct`, i.e. https://github.com/dart-lang/ffigen/issues/68#issuecomment-784656084

```c
// C struct
struct TW_VERSION {
  char[34] info;
}
```

```dart
// dart class
class TW_VERSION extends Stuct {}
```

I could get the struct address but fail to perform static_cast like operation on it
