### ISSUE TITLE
IsolateFunction async

### ISSUE THREAD

**Issue by MoonRune** [ekibun/flutter_qjs#19]
await setToGlobalObject.invoke(["http", (String url) {
        return Dio().get(url).then((response) => response.data);
      }]);
in my demo, it return future<String> instead of future.
event i change the code to:
      await setToGlobalObject.invoke(["http", (String url) async {
        return (await Dio().get(url)).toString();
      }]);
is there any way to get reusult?

**Comment by ekibun** [comment]
Plugin wraps the parameters and returns automatically. Both your demo returns `Future` in the function, and you would get `Promise` in Javascript side. you can get result with await **IN JAVASCRIPT**:
```javascript
(async (url) => {
   var rsp = await http(url);
   /** or **/
  http(url).then((rsp) => {
     /** your code here **/
  })
})()
```

If you want to get the return value directly. you **SHOULD NOT** use async syntax or return Future in the function:
```dart
await setToGlobalObject.invoke(["http", (String url) {
  return "directly";
}]);
```

**Comment by MoonRune** [comment]
thanks.
i want my js code run after dart future task done.
it should be related with dart microtask .
