### ISSUE TITLE
为什么不用dart:ffi

### ISSUE THREAD

**Issue by neeboo** [ekibun/flutter_qjs#2]
感觉会更好一些

**Comment by ekibun** [comment]
https://github.com/dart-lang/sdk/issues/36730
与其给qjs函数全包一遍指针，感觉不如直接C++写的快

**Comment by neeboo** [comment]
> [dart-lang/sdk#36730](https://github.com/dart-lang/sdk/issues/36730)
> 与其给qjs函数全包一遍指针，感觉不如直接C++写的快

也就是一些wrapper，学习了一下你的异步处理，感谢分享
