### ISSUE TITLE
[BUG] JSTag value mismatching because of int32 value conversion  

### ISSUE THREAD

**Issue by narumishi** [ekibun/flutter_qjs#23]
After upgrading to flutter 2.7, a string eval result always return null.  Flutter 2.6 works.

Android real device(arm64) has such error. Windows, macOS, iOS and Android Emulator(Google x86_64) work.

Tries to test on `flutter_js`, find it was extended of this package, the same error there:
https://github.com/abner/flutter_js/issues/65

As the solution provided in above issue, convert int_32 to int_64, everything works.

int_32 and int_64 variables with same value won't be matched in switch-case ? I'm not sure anywhere else may have similar bug because of int_32.

**Comment by Unicellular-SU** [comment]
I have the same problem.

**Comment by narumishi** [comment]
https://github.com/abner/flutter_js/commit/d4aa7238e99eb30edb0924394f26af7a7711d316

That's quite a quick fix. If you have time, please release a new version.

**Comment by narumishi** [comment]
Could you pls apply the quick fix for the new release?

**Comment by ekibun** [comment]
Sorry for late reply.

I have upgraded Flutter to 2.11 and tested in my Huawei device and no errors found. Is the bug still existed?

**Comment by narumishi** [comment]
It seems fixed in the latest flutter :thinking:
