### ISSUE TITLE
SetInterruptHandler and SetMemoryLimit missing

### ISSUE THREAD

**Issue by Matthiee** [ekibun/flutter_qjs#25]
I want to configure the memory limit and define a custom interrupt handler in QuickJS.

To do this the following functions need to be implemented:

- JS_SetMemoryLimit
- JS_SetInterruptHandler

Example: 
```javascript
// this script will keep running
while (true) { }
```

With a custom interrupt handler, it is possible to prevent abuse.

**Comment by ekibun** [comment]
Done, I prefered to wrap the `JS_SetInterruptHandler` in cpp code instead exporting it to the dart side, Example can be found in:
https://github.com/ekibun/flutter_qjs/blob/32aac42c194bd9631fb44e0582e6fde1778807d0/test/flutter_qjs_test.dart#L124-L153
