### ISSUE TITLE
Standard Library?

### ISSUE THREAD

**Issue by rodydavis** [ekibun/flutter_qjs#27]
Having trouble finding things like FileReader, setTimeout, fetch, http requests, and requestIdleCallback?

According to the docs this should be included:

https://bellard.org/quickjs/quickjs.html

Are these missing from the FFI calls? Or is there a way I can make the network requests on the flutter side when fetch is invoked?

**Comment by ekibun** [comment]
The standard library in quickjs is crude and not included in this plugin. I recommand you implement them on dart side with the following steps: 
1. evaluate a function that change the global this
2. call the JsInvokable with dart function
```
final setToGlobalObject = await engine.evaluate("(key, val) => { this[key] = val; }");
await setToGlobalObject.invoke(["http", (String url) {
  return Dio().get(url).then((response) => response.data);
}]);
setToGlobalObject.free();
```
For more information please check https://github.com/ekibun/flutter_qjs#use-dart-function-breaking-change-in-v030 .

Or you can use flutter_js instead. That implementation provides some standard functions.

**Comment by rodydavis** [comment]
I don't mind doing the networking on the dart side. I saw the example in the docs, could you share another example? 

For example if I have a the following code `fetch("https://...").then(res => res.json());` and want to evaluate it, how can I use Dio when fetch is invoked? 

When I try to evaluate it will say it's not defined. Can I pass a dart function to the script at evaluation time?

**Comment by ekibun** [comment]
Fristly, you need to pass your dart function right after `FlutterQjs` object initialized.
```dart
final engine = FlutterQjs();
engine.dispatch();
final setToGlobalObject = await engine.evaluate("(key, val) => { this[key] = val; }");
await setToGlobalObject.invoke(["fetch", (String url) async {
  return Dio().get(url).then((response) => response.toString());
}]);
setToGlobalObject.free();
```
Then, all the evaluation can access the fetch function:
```dart
print(await engine.evaluate("fetch(`https://reqbin.com/echo/get/json`).then(res => `The response is: \${res}`)"));
```
You should get the response string like that:
```
The response is: {"success":"true"}
```

**Comment by rodydavis** [comment]
Oh this is super helpful!! Thank you, definitely seeing the pieces and how they fit together now. 🔥

Thank you very much! I also had a prototype with headless in app web view as well. 

Based on my research into this, I might write a blog post on it!
