### ISSUE TITLE
ES6 import相关

### ISSUE THREAD

**Issue by AceCodeE** [ekibun/flutter_qjs#28]
```javascript
// 可以支持下面的引入方式?
import { MineFunc } from "Mine";

// 假设有console.log(MineFunc()); // MineFunc() = 256;
console.log(MineFunc());
```

```
// 然后在dart端Handler进行处理?
```

**Comment by ekibun** [comment]
js模块文件的话实现一下 https://github.com/ekibun/flutter_qjs#use-modules
dart你想怎么handle？quickjs的模块没法传参，想做的话还是要先导入一个全局变量，然后在模块里用，我是不建议把和dart的接口暴露出来的

**Comment by AceCodeE** [comment]
> js模块文件的话实现一下 https://github.com/ekibun/flutter_qjs#use-modules 然后eval的时候用import和模块名调用，直接evaluate模块没法运行的。
> 
> dart你想怎么handle？quickjs的模块没法传参，想做的话还是要先导入一个全局变量，然后在模块里用，我是不建议把和dart的接口暴露出来的

```
// 目前是这样import module;
import("hello").then(({default: greet}) => greet("world"));

// 我的意思是能支持像以下方式解构 // 支持Js中 */as/from这几个关键词 
import { MineFunc } from Mine;
// 比如我的JS文件内容的line1 >>> import m1 from './01_m1.js'
// 然后在 dart 的 moduleHandler 
final engine = FlutterQjs(
  moduleHandler: (String module) {
    if(module == "./01_m1.js")
      return "export default (name) => `hello \${name}!`;";
    throw Exception("Module Not found");
  },
);

// 这应该是ES6 可以提供的,因为我查看QuickJS文档是可以像import { MineFunc } from Mine;这种方式导入使用的,而不是异步加载;

// 汉语不怎么好,不知道表达清楚了没
```

**Comment by AceCodeE** [comment]
> js模块文件的话实现一下 https://github.com/ekibun/flutter_qjs#use-modules 然后eval的时候用import和模块名调用，直接evaluate模块没法运行的。
> 
> dart你想怎么handle？quickjs的模块没法传参，想做的话还是要先导入一个全局变量，然后在模块里用，我是不建议把和dart的接口暴露出来的

// 目前是这样import module;
import("hello").then(({default: greet}) => greet("world"));
// 添加一个
import greet from "hello";

greet("world);

**Comment by ekibun** [comment]
你在modulehandler里返回的字符串可以这么写，具体参考：
https://github.com/ekibun/flutter_qjs/blob/232ea07e895f24f0fc6b6f521fb134164d7c5133/test/flutter_qjs_test.dart#L124-L139

**Comment by AceCodeE** [comment]
> 你在modulehandler里返回的字符串可以这么写，具体参考：
> 
> https://github.com/ekibun/flutter_qjs/blob/232ea07e895f24f0fc6b6f521fb134164d7c5133/test/flutter_qjs_test.dart#L124-L139

谢谢，原来我没认真看文档;
