### ISSUE TITLE
Linux test produces `Failed to load dynamic library 'test/build/libffiquickjs.so'`

### ISSUE THREAD

**Issue by misha** [ekibun/flutter_qjs#42]
Here's what I've done:

- Added `flutter_qjs` to `pubspec.yaml`.
- Created a test that constructs a `FlutterQjs` object, calls `dispatch`, then `evaluate`.
- Run `flutter test`.

I am running on Ubuntu Linux. The error is as follows:

```
  Invalid argument(s): Failed to load dynamic library 'test/build/libffiquickjs.so': 
    test/build/libffiquickjs.so: cannot open shared object file: No such file or directory
  dart:ffi                                   new DynamicLibrary.open
  package:flutter_qjs/src/ffi.dart 121:30    _qjsLib
  package:flutter_qjs/src/ffi.dart           _qjsLib
  package:flutter_qjs/src/ffi.dart 160:19    _jsNewRuntime
  package:flutter_qjs/src/ffi.dart           _jsNewRuntime
  package:flutter_qjs/src/ffi.dart 205:14    jsNewRuntime
  package:flutter_qjs/src/engine.dart 49:16  FlutterQjs._ensureEngine
  package:flutter_qjs/src/engine.dart 166:5  FlutterQjs.evaluate
```

The line `ffi.dart 121:30` appears to define a preset location for QuickJS depending on the platform. 

Am I using this package correctly? The README does not indicate any sort of additional setup that would generate a shared object file in that location. I have not performed any specific QuickJS setup.

**Comment by Matthiee** [comment]
@misha When running from inside tests the binaries need to be present inside the `/test/build/` folder. This needs to be done manually see some example here https://github.com/ekibun/flutter_qjs/blob/master/test/flutter_qjs_test.dart#L77-L123

When running the full Flutter app it will be generated automatically

**Comment by misha** [comment]
@Matthiee Thanks for the response, closing!
