### ISSUE TITLE
[Windows] Compiler Error C2099: "initializer is not a constant"  in release/profile mode

### ISSUE THREAD

**Issue by narumishi** [ekibun/flutter_qjs#7]
Compile error C2099 in release and profile mode on windows, Debug mode and all build modes for android/ios/macOS are passed.
Build release output:
```
<project_path>\windows\flutter\ephemeral\.plugin_symlinks\flutter_qjs\cxx\quickjs\quickjs.c(41791,1): error C2099: initializer is not a constant [<project_path>\build\windows\plugins\flutter_qjs\quickjs.vcxproj]
<project_path>\windows\flutter\ephemeral\.plugin_symlinks\flutter_qjs\cxx\quickjs\quickjs.c(41792,1): error C2099: initializer is not a constant [<project_path>\build\windows\plugins\flutter_qjs\quickjs.vcxproj]
```
The code at quickjs.c(41791|41792):
```
static const JSCFunctionListEntry js_math_funcs[] = {
    // skip lines
    JS_CFUNC_SPECIAL_DEF("floor", 1, f_f, floor ),
    JS_CFUNC_SPECIAL_DEF("ceil", 1, f_f, ceil ),
```

According to https://github.com/codeplea/tinyexpr/issues/34, 
-  change `floor` and `ceil` to `floorl` and `ceill`(for long double type), error disappear but warning of mismatch of parameter type
- add `#pragma function (ceil)` and `#pragma function (floor)` before `static const JSCFunctionListEntry`, error disappear.

<details>
    <summary>flutter doctor -v</summary>
```
[✓] Flutter (Channel master, 1.26.0-2.0.pre.167, on Microsoft Windows [Version 10.0.19042.685], locale zh-CN)
    • Flutter version 1.26.0-2.0.pre.167 at D:\Projects\sdk\flutter
    • Framework revision d3a2259541 (9 days ago), 2020-12-31 15:14:03 -0500
    • Engine revision 82b4ae86d6
    • Dart version 2.12.0 (build 2.12.0-179.0.dev)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at D:\Projects\sdk\Android\Sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = D:\Projects\sdk\Android\Sdk
    • Java binary at: C:\Users\narumi\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-1\201.6953283\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Visual Studio - develop for Windows (Visual Studio Enterprise 2019 16.8.3)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise
    • Visual Studio Enterprise 2019 version 16.8.30804.86
    • Windows 10 SDK version 10.0.18362.0

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\narumi\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-1\201.6953283
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.52.1)
    • VS Code at C:\Users\narumi\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)       • windows       • windows-x64    • Microsoft Windows [Version 10.0.19042.685]
    • Edge (web)              • edge          • web-javascript • Microsoft Edge 87.0.664.75

! Doctor found issues in 1 category.
```
</details>

```
```

**Comment by ekibun** [comment]
Thanks

**Comment by d00z3l** [comment]
Thanks, I tested on with your fork and it works, can build with `--release`

**Comment by narumishi** [comment]
The problem suddenly occur again. Local building passed, but github workflow failed, which is successful several days ago.

```
[        ]   D:\a\chaldea\chaldea\windows\flutter\ephemeral\.plugin_symlinks\flutter_qjs\
cxx\quickjs\quickjs.c(41831,1): error C2099: initializer is not a constant 
[D:\a\chaldea\chaldea\build\windows\plugins\flutter_qjs\quickjs.vcxproj]
```

line 41831
```c
    JS_CFUNC_SPECIAL_DEF("log2", 1, f_f, log2 ),
```
Build log:
https://github.com/chaldea-center/chaldea/runs/6422757907?check_suite_focus=true

Wonder why and what kind of functions are facing this problem?

**Comment by narumishi** [comment]
VS2019 builds ok, after upgrade to VS2022(17.2.32505.173), the error occurs, and `#pragma function (log2)` also works.

**Comment by ekibun** [comment]
PR plz

**Comment by narumishi** [comment]
Before patching, I wonder will this problem increasing while VS updating its components or libs? 
Is this the only way to fix it one by one?
( I dont have C/C++ experience)

**Comment by ekibun** [comment]
I'm not familiar with C++, either.
In https://github.com/ekibun/flutter_qjs/commit/232ea07e895f24f0fc6b6f521fb134164d7c5133, I remove the pragma and [disable the intrinsic function optimization](https://docs.microsoft.com/en-us/cpp/build/reference/oi-generate-intrinsic-functions). The windows release build of the example compiles successfully. Please check again in your application.

**Comment by ekibun** [comment]
I’m sorry but I currently don’t have bandwidth in maintaining this library, I am fraud a release won’t happen in the near future. Please feel free to fork this repo and make changes though.

**Comment by narumishi** [comment]
The only troublesome stuff is that this repo using submodule and pub wont clone it if using git deps, thus every update or workflow needs to manually init submodule.

If no more fix recently, why not just release a minor version to fix it? I guess it only takes several minutes to run dart pub publish?
